### ISSUE TITLE
关于安装 node_modules

### ISSUE THREAD

**Issue by Weiy-Geek** [ChiChou/ujscert#1]
在您前面的Readme中“**可先在具有 node 环境的计算机上执行 npm install，随后复制 web/node_modules 目录即可。**”
我不明白复制 web/node_modules 目录，在那里复制？node安装目录 还是 Npm 安装目录。
我已成功按上nodejs和npm：
[root@localhost web]# node --version
v4.6.1
[root@localhost web]# npm --version
2.15.9
[root@localhost web]# npm install
jquery-jsonview@1.2.3 node_modules/jquery-jsonview
font-awesome@4.7.0 node_modules/font-awesome
tether@1.3.7 node_modules/tether
jquery@2.2.4 node_modules/jquery
bootstrap@4.0.0-alpha.5 node_modules/bootstrap

**Comment by Weiy-Geek** [comment]
#我将/lib/node_modules复制到了 ujscert 目录中，这样对吗？
`root@localhost ujscert]# ll
总用量 12
drwxr-xr-x. 5 root root   60 10月 25 00:34 docker
-rw-r--r--. 1 root root  494 10月 25 00:34 docker-compose.yml
drwxr-xr-x. 3 root root   16 10月 25 22:26 node_modules
-rw-r--r--. 1 root root 1037 10月 25 00:34 production-example.yml
-rw-r--r--. 1 root root 2235 10月 25 00:34 README.md
drwxr-xr-x. 6 root root  103 10月 25 22:08 web
`

**Comment by ChiChou** [comment]
复制 node_modules 指的是从自己的开发机部署到生产环境这种部署。考虑到只用来做前端管理，没有必要在生产环境安装 node.js。

如果只是在自己的机器上做开发和 demo，只需要 `cd web; npm install` 即可。
