### ISSUE TITLE
关于zhparser-docker中./bulid.sh报错

### ISSUE THREAD

**Issue by Weiy-Geek** [ChiChou/ujscert#3]
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Cannot initiate the connection to deb.debian.org:80 (2001:4f8:8:36::1deb:22). - connect (101: Network is unreachable) [IP: 2001:4f8:8:36::1deb:22 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Cannot initiate the connection to deb.debian.org:80 (2001:4f8:8:36::1deb:22). - connect (101: Network is unreachable) [IP: 2001:4f8:8:36::1deb:22 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  Cannot initiate the connection to deb.debian.org:80 (2001:4f8:8:36::1deb:22). - connect (101: Network is unreachable) [IP: 2001:4f8:8:36::1deb:22 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  Cannot initiate the connection to deb.debian.org:80 (2001:4f8:8:36::1deb:22). - connect (101: Network is unreachable) [IP: 2001:4f8:8:36::1deb:22 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Weiy-Geek** [comment]
2016/10/26 10:38:38 Error resolving syscall name execveat: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name getrandom: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name memfd_create: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name renameat2: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name sched_getattr: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name sched_setattr: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name seccomp: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name cacheflush: could not resolve name to syscall - ignoring syscall.
2016/10/26 10:38:38 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.


**我是centos7的系统。**

**Comment by ChiChou** [comment]
看日志应该是您电脑上 DNS 的问题，解析出了 IPv6 的地址但可能网络不支持 IPv6（或者其他原因无法连接到 debian 源）。
