### ISSUE TITLE
如何建立docker tag 的image 为zhparser

### ISSUE THREAD

**Issue by Weiy-Geek** [ChiChou/ujscert#4]
[root@localhost ujscert]# docker-compose build && docker-compose up -d
ERROR: Service 'db' failed to build: Error: image library/postgresql-zhparser not found

**Comment by ChiChou** [comment]
我 push 了一个构建好的 docker image 到 docker hub，可以使用
`docker pull codecolorist/postgresql-zhparser` 获取。然后 `docker tag 17318ed6efbd codecolorist/postgresql-zhparser` 将其改名为 postgresql-zhparser
